[theme]
primaryColor = "#8ab4f8"
backgroundColor = "#0b0f17"
secondaryBackgroundColor = "#1e2a44"
textColor = "#ffffff"

[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false
